name = "mitty-antenna-rs"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-26"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "mitty-antenna-prod"
database_id = "7d64564c-fb6c-4acd-be36-79f91282528b"

[triggers]
crons = [ "*/10 * * * *"]

[observability.logs]
enabled = true
